# Generated by Django 5.0.6 on 2025-05-24 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('one', 'level_one'), ('two', 'level_two'), ('three', 'level_three'), ('other', 'other')], default='one', max_length=12)),
                ('detail', models.TextField()),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('distance', models.IntegerField(default=0)),
                ('route_prize', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='user.branch')),
                ('last_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='user.branch')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10, null=True)),
                ('Model', models.CharField(max_length=100)),
                ('sit_number', models.IntegerField(default=0)),
                ('picture', models.ImageField(upload_to='vehicle_management/vehicle_image')),
                ('is_active', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('insurance_doc', models.ImageField(null=True, upload_to='vehicle_management/insurance_doc')),
                ('insurance_date', models.DateField(null=True)),
                ('long', models.BooleanField(default=False)),
                ('detail', models.CharField(max_length=200, null=True)),
                ('payment_rate', models.DecimalField(decimal_places=2, default=1, max_digits=9)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.branch')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_management.location')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_management.route')),
                ('types', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_management.type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExitSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('passenger_count', models.IntegerField()),
                ('status', models.CharField(choices=[('p', 'Pending'), ('a', 'Approved'), ('r', 'Rejected'), ('c', 'Completed')], default='p', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_code', models.CharField(blank=True, max_length=255)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_from', to='user.branch')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_to', to='user.branch')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_management.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='vehicle_management/doc')),
                ('did', models.CharField(max_length=100, unique=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_doc', to='vehicle_management.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Queues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('position', models.IntegerField(default=0)),
                ('current_passengers', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('BOARDING', 'Boarding'), ('FULL', 'Full'), ('DEPARTED', 'Departed')], default='WAITING', max_length=10)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_branches', to='user.branch')),
                ('dest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_destinations', to='user.branch')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_management.type')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_management.vehicle')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('date', 'branch', 'dest', 'position')},
            },
        ),
    ]
