# Generated by Django 5.0.6 on 2025-04-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0002_vehicle_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='level',
            field=models.CharField(choices=[('lo', 'level_one'), ('lt', 'level_two'), ('lth', 'level_three'), ('oo', 'other')], default='lo', max_length=12),
        ),
    ]
