# Generated by Django 5.0.6 on 2025-05-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0002_alter_vehicle_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='tracking',
            field=models.BooleanField(default=False),
        ),
    ]
