# Generated by Django 5.0.6 on 2025-04-02 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_location_branch_location'),
        ('vehicle_management', '0003_alter_type_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.location'),
        ),
    ]
