# Generated by Django 5.0.6 on 2025-06-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_locations_tracking'),
        ('vehicle_management', '0003_vehicle_tracking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queues',
            unique_together={('date', 'branch', 'dest')},
        ),
    ]
