# Generated by Django 5.0.6 on 2025-04-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0005_vehicle_is_active_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='location',
        ),
    ]
