# Generated by Django 5.0.6 on 2025-04-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0007_remove_location_vehicle_vehicle_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
