# Generated by Django 5.0.6 on 2025-04-02 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_location_branch_location'),
        ('vehicle_management', '0009_alter_vehicle_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='user.branch')),
                ('last_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='user.branch')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_management.route'),
        ),
    ]
