# Generated by Django 5.0.6 on 2025-04-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0012_vehicle_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='route',
        ),
    ]
