# Generated by Django 5.0.6 on 2025-04-02 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0013_remove_vehicle_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_management.route'),
        ),
    ]
