# Generated by Django 5.0.6 on 2025-04-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0014_vehicle_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
