# Generated by Django 5.0.6 on 2025-04-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0015_alter_vehicle_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='level',
            field=models.CharField(choices=[('one', 'level_one'), ('two', 'level_two'), ('three', 'level_three'), ('other', 'other')], default='one', max_length=12),
        ),
    ]
