# Generated by Django 5.0.6 on 2025-04-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0016_alter_type_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='prize',
            new_name='route_prize',
        ),
    ]
