# Generated by Django 5.0.6 on 2025-04-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0019_vehicle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='insurance_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_doc',
            field=models.ImageField(null=True, upload_to='vehicle_management/insurance_doc'),
        ),
    ]
