# Generated by Django 5.0.6 on 2025-04-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0020_vehicle_insurance_date_vehicle_insurance_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
