# Generated by Django 5.0.6 on 2025-04-27 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_employeedetail_emergency_contact_and_more'),
        ('vehicle_management', '0023_exitslip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitslip',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_from', to='user.branch'),
        ),
        migrations.AlterField(
            model_name='exitslip',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_to', to='user.branch'),
        ),
    ]
