# Generated by Django 5.0.6 on 2025-04-02 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0009_alter_user_date_joined'),
        ('vehicle_management', '0003_alter_type_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.BigIntegerField()),
                ('latitude', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='alert_not',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('types', models.CharField(choices=[('r', 'request'), ('s', 'response')], default='r', max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.branch')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_management.vehicle')),
            ],
        ),
    ]
