# Generated by Django 5.0.6 on 2025-04-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='location',
        ),
    ]
