# Generated by Django 5.0.6 on 2025-05-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('r', 'Request'), ('s', 'Response'), ('a', 'Alert'), ('p', 'Payment')], default='a', max_length=10),
        ),
    ]
