# Generated by Django 5.0.6 on 2025-04-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
