# Generated by Django 5.0.6 on 2025-05-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0006_alter_notification_options_message'),
        ('vehicle_management', '0024_alter_exitslip_from_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='types',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('r', 'Request'), ('s', 'Response'), ('a', 'Alert')], default='a', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_management.vehicle'),
        ),
    ]
