# Generated by Django 5.0.6 on 2025-04-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nidUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('FAN', models.CharField(default='810AC056', editable=False, max_length=20, unique=True)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
