# Generated by Django 5.0.6 on 2025-05-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niduser',
            name='picture',
            field=models.ImageField(null=True, upload_to='api/image/profile'),
        ),
    ]
