# Generated by Django 5.0.6 on 2025-04-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niduser',
            name='FAN',
            field=models.CharField(default='552133B3', editable=False, max_length=20, unique=True),
        ),
    ]
