# Generated by Django 5.0.6 on 2025-04-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_niduser_fan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niduser',
            name='FAN',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
    ]
