# Generated by Django 5.0.6 on 2025-04-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_niduser_fan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niduser',
            name='FAN',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
