# Generated by Django 5.0.6 on 2025-04-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_niduser_fan'),
    ]

    operations = [
        migrations.AddField(
            model_name='niduser',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
