# Generated by Django 5.0.6 on 2025-05-24 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('m', 'main'), ('b', 'branch')], default='b', max_length=15)),
                ('status', models.CharField(choices=[('a', 'Active'), ('m', 'Maintenance'), ('i', 'Inactive')], default='a', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(null=True)),
                ('type', models.CharField(choices=[('d', 'driving_license'), ('p', 'passport'), ('i', 'institute_id'), ('g', 'goverment id'), ('o', 'other')], default='o', max_length=12)),
                ('did', models.CharField(max_length=100, unique=True)),
                ('doc', models.FileField(upload_to='user/employee_doc/credentials')),
            ],
        ),
        migrations.CreateModel(
            name='employeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100, null=True)),
                ('Lname', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(default='', max_length=100)),
                ('picture', models.ImageField(null=True, upload_to='user/employee_doc/profile')),
                ('Emergency_contact_name', models.CharField(max_length=100, null=True)),
                ('Emergency_contact', models.CharField(max_length=100, null=True)),
                ('Work_experience', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('code', models.CharField(blank=True, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.CharField(choices=[('a', 'admin'), ('s', 'sub_admin'), ('u', 'user'), ('d', 'driver')], default='u', max_length=12)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateField(auto_now_add=True, null=True)),
                ('phone_number', models.BigIntegerField(default=0, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('nid', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.niduser')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.branch')),
                ('credentials', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.credentials')),
                ('employee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.employeedetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.locations'),
        ),
    ]
