# Generated by Django 5.0.6 on 2025-05-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='tracking',
            field=models.BooleanField(default=False),
        ),
    ]
