# Generated by Django 5.0.6 on 2025-03-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_employeedetail_user_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='position',
            field=models.CharField(default='operator', max_length=100),
        ),
    ]
