# Generated by Django 5.0.6 on 2025-03-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_employeedetail_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='Fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='Lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
    ]
