# Generated by Django 5.0.6 on 2025-03-31 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='date',
        ),
    ]
