# Generated by Django 5.0.6 on 2025-04-06 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_niduser_fan'),
        ('user', '0010_location_branch_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.niduser'),
        ),
    ]
