# Generated by Django 5.0.6 on 2025-04-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_branch_location_alter_location_latitude_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='location',
            new_name='locations',
        ),
    ]
