# Generated by Django 5.0.6 on 2025-04-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_location_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('m', 'Maintenance'), ('i', 'Inactive')], default='a', max_length=10),
        ),
    ]
