# Generated by Django 5.0.6 on 2025-04-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_branch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='picture',
            field=models.ImageField(null=True, upload_to='user/employee_doc/profile'),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='doc',
            field=models.FileField(upload_to='user/employee_doc/credentials'),
        ),
    ]
