# Generated by Django 5.0.6 on 2025-04-19 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_employeedetail_picture_alter_credentials_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='last_name',
        ),
    ]
