# Generated by Django 5.0.6 on 2025-04-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_credentials_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
