# Generated by Django 5.0.6 on 2025-04-19 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_credentials_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='credentials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.credentials'),
        ),
    ]
