# Generated by Django 5.0.6 on 2025-04-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_credentials_user_user_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='Emergency_contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='Emergency_contact_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='Work_experience',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
