# Generated by Django 5.0.6 on 2025-05-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_date', models.DateTimeField(auto_now_add=True)),
                ('ticket_type', models.CharField(choices=[('L', 'LONG'), ('S', 'SHORT')], default='S', max_length=10)),
                ('Quantity', models.IntegerField(default=1)),
                ('takeoff_time', models.TimeField(null=True)),
                ('takeoff_date', models.DateField(null=True)),
                ('total_prize', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='travelhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
