# Generated by Django 5.1.7 on 2025-03-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('first_destination', models.CharField(max_length=50)),
                ('last_destination', models.CharField(max_length=50)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('bought_date', models.DateTimeField(auto_now_add=True)),
                ('additional', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
            ],
        ),
    ]
