# Generated by Django 5.0.6 on 2025-03-31 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
        ('user', '0002_user_is_staff_alter_user_password'),
        ('vehicle_management', '0002_vehicle_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='additional',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='time',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='ticket',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle_management.type'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='takeoff_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='takeoff_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='first_destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='user.branch'),
        ),
        migrations.AlterField(
            model_name='route',
            name='last_destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='user.branch'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='travelhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.ticket')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_management.vehicle')),
            ],
        ),
    ]
