# Generated by Django 5.0.6 on 2025-03-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_ticket_additional_remove_ticket_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='last_destination',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
