# Generated by Django 5.0.6 on 2025-03-31 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_route_last_destination'),
        ('user', '0002_user_is_staff_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='last_destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='user.branch'),
        ),
    ]
