# Generated by Django 5.0.6 on 2025-04-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_route_last_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='used',
        ),
    ]
