# Generated by Django 5.0.6 on 2025-04-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_ticket_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelhistory',
            name='total_prize',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='travelhistory',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
