# Generated by Django 5.0.6 on 2025-04-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_travelhistory_total_prize_travelhistory_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='first_destination',
        ),
        migrations.RemoveField(
            model_name='route',
            name='last_destination',
        ),
    ]
