# Generated by Django 5.0.6 on 2025-04-02 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_route_first_destination_and_more'),
        ('vehicle_management', '0010_route_vehicle_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='route', to='vehicle_management.route'),
        ),
        migrations.DeleteModel(
            name='route',
        ),
    ]
