# Generated by Django 5.0.6 on 2025-04-02 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_ticket_route_delete_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelhistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.ticket'),
        ),
    ]
