# Generated by Django 5.0.6 on 2025-04-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_travelhistory_ticket'),
        ('vehicle_management', '0012_vehicle_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route', to='vehicle_management.route'),
        ),
    ]
