# Generated by Django 5.0.6 on 2025-04-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_ticket_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('L', 'LONG'), ('S', 'SHORT')], default='S', max_length=10),
        ),
    ]
