# Generated by Django 5.0.6 on 2025-04-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_prize',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
