# Generated by Django 5.0.6 on 2025-04-10 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_ticket_total_prize'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelhistory',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.payment'),
        ),
    ]
