# Generated by Django 5.0.6 on 2025-04-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_travelhistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelhistory',
            name='total_prize',
        ),
    ]
