# Generated by Django 5.0.6 on 2025-04-18 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_remove_travelhistory_total_prize'),
        ('user', '0014_branch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelhistory',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.branch'),
        ),
    ]
