# Generated by Django 5.0.6 on 2025-05-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'pending'), ('c', 'completed')], default='p', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('transaction_id', models.CharField(max_length=50)),
                ('types', models.CharField(choices=[('i', 'income'), ('e', 'expense'), ('t', 'tax')], default='i', max_length=10)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
    ]
