# Generated by Django 5.0.6 on 2025-04-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='types',
            field=models.CharField(choices=[('i', 'income'), ('e', 'expense'), ('t', 'tax')], default='i', max_length=10),
        ),
    ]
