# Generated by Django 5.0.6 on 2025-04-19 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_status_payment_user'),
        ('vehicle_management', '0021_alter_vehicle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle_management.vehicle'),
        ),
    ]
